### ISSUE TITLE
Use nio Files/Paths

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/MobilitySimulator#96]
I think it could make sense to work with `File`s here, as you can extend them like this: `File file2 = new File(file1, "subdir");`. This would also add type safety (files are recognizable by type, as they're not just represented by Strings). I'd suggest opening a new issue for this

_Originally posted by @sebastian-peter in https://github.com/ie3-institute/MobilitySimulator/pull/79#discussion_r976909757_

**Comment by sebastian-peter** [comment]
I adapted `PathsAndSources` to use nio Files/Paths in #75. These are preferable over using legacy `java.io.File`. There are some spots in this project left where Strings are still used and could also be replaced by paths.

**Comment by t-ober** [comment]
Resolved by #75

**Comment by sebastian-peter** [comment]
As I said in the previous comment, there's many places where we still use Strings and/or `java.io.File`, so this is not solved imho
